[book]
authors = ["Benjamin Reed"]
language = "en"
multilingual = false
src = "src"
title = "The Git Cookbook"

[build]
build-dir = "docs"

[output.html]
git-repository-url = "https://github.com/RangerRick/git-cookbook"
