version: 2.1

commands:
  restore-cargo:
    steps:
      - restore_cache:
          name: Restore Rust Cargo Cache
          keys:
            - cargo-cache-v1-{{ .Branch }}-{{ .Revision }}
            - cargo-cache-v1-{{ .Branch }}-
            - cargo-cache-v1-
      - run: cargo --version
      - run: cargo install mdbook
  save-cargo:
    steps:
      - save_cache:
          name: Save Rust Cargo Cache
          key: cargo-cache-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - "/usr/local/cargo"

  do-build:
    steps:
      - run:
          name: Run Build
          command: |
            /usr/local/cargo/bin/mdbook clean
            /usr/local/cargo/bin/mdbook build

jobs:
  build:
    docker:
      - image: rust:latest
        environment:
          TZ: "America/New_York"
    steps:
      - checkout
      - restore-cargo
      - do-build
      - save-cargo
  pages:
    docker:
      - image: rust:latest
        environment:
          TZ: "America/New_York"
    steps:
      - checkout
      - run:
          name: Set up Git config
          command: |
            git config user.name 'CircleCI Automated Commit'
            git config user.email 'github@raccoonfink.com'
      - run:
          name: Merge main to GitHub pages
          command: |
            git fetch --all
            git checkout pages
            git reset --hard origin/pages
            git merge -m 'automated merge from main -> pages' --log main
      - restore-cargo
      - do-build
      - add_ssh_keys:
          fingerprints:
            - "e2:9d:2b:32:9c:46:e1:c4:df:16:e1:ed:51:bd:63:a4"
      - run:
          name: Commit and Push Updated Artifacts
          command: |
            git add -A
            if [ `git diff HEAD | wc -l` -gt 0 ]; then
              echo "changes detected; committing updated docs/"
              git commit -m 'build: automated merge from main'
            fi
            git push origin pages:pages

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - pages:
          requires:
            - build
          filters:
            branches:
              only:
                - main
